AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for the AWS Lambda function

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev
  AWSRegion:
    Type: String
    Description: AWS Region
    Default: us-east-1
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function
    Default: 'data-processor'
  LambdaCodeBucket:
    Type: String
    Description: Name of the S3 bucket where the Lambda code is located
    Default: ${Environment}-${AWSRegion}-artifacts-bucket
  LambdaCodeKey:
    Type: String
    Description: Name of the S3 key where the Lambda code is located
    Default: lambda.zip


Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Description: 'Lambda funtion for data processing'
      Handler: cloud_data_processing.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Runtime: python3.6

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-${LambdaFunctionName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${Environment}-${LambdaFunctionName}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${LambdaCodeBucket}/*
                  - !Sub arn:aws:s3:::${LambdaCodeBucket}

